(node:18495) UnhandledPromiseRejectionWarning: Error: Transaction has been reverted by the EVM:
{
  "blockHash": "0x6c4d2a92e11a48a2c723764a107d46f4230465520efbaf22f89d4a3de347066c",
  "blockNumber": 3003276,
  "contractAddress": null,
  "cumulativeGasUsed": 21000,
  "from": "0x32eebc8fd8cb9353eeb5e0ea4ee124dd66ee6a37",
  "gasUsed": 21000,
  "logs": [],
  "logsBloom": "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  "status": true,
  "to": "0x9d851444143ee6fb8c535b183c3ee191e79666f5",
  "transactionHash": "0x853d5398317a384b9ec035428203d7ade348abde267c1a38768cc85b4009996b",
  "transactionIndex": 0
}
    at SafeSubscriber._next (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/web3-core-method/dist/web3-core-method.cjs.js:1017:32)
    at SafeSubscriber.__tryOrUnsub (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/rxjs/internal/Subscriber.js:207:16)
    at SafeSubscriber.next (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/rxjs/internal/Subscriber.js:145:22)
    at Subscriber._next (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/rxjs/internal/Subscriber.js:89:26)
    at Subscriber.next (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/rxjs/internal/Subscriber.js:66:18)
    at TransactionObserver.emitNext (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/web3-core-method/dist/web3-core-method.cjs.js:438:16)
    at _callee2$ (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/web3-core-method/dist/web3-core-method.cjs.js:408:24)
    at tryCatch (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.(anonymous function) [as next] (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/alexcg/newton/newchain-sdk-example/examples/nodesdk/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
(node:18495) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:18495) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
